### ISSUE TITLE
Compilation error with Intel 15.0

### ISSUE THREAD

**Issue by shampton-crc** [idaholab/moose#7578]
### Description of the enhancement or error report

Current version of code fails to compile with Intel 15.0 due to error 809, as described here:
https://software.intel.com/en-us/articles/cdiag809/
### Rationale for the enhancement or information for reproducing the error

Followed installation instructions until:

cd test
make -j8

Errors like the following appear:

In file included from ~/moose-base/moose/framework/include/outputs/formatters/InputFileFormatter.h(18),
                 from ~/moose-base/moose/framework/src/actions/ActionWarehouse.C(19):
~/moose-base/moose/framework/include/utils/SyntaxTree.h(34): error #809: exception specification for virtual function "SyntaxTree::~SyntaxTree" is incompatible with that of overridden function "SyntaxFormatterInterface::~SyntaxFormatterInterface"
    virtual ~SyntaxTree();
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by jwpeterson** [comment]
This could be an issue with the "=default" we've used in a few places on destructors.  Can you try taking those out, and seeing if it fixes your compilation issues?

**Comment by jwpeterson** [comment]
BTW, the link you posted says that this should be a warning...

**Comment by permcody** [comment]
Intel compilers are no longer supported - Closing this ticket.
