### PR TITLE
Remove redundant template qualifier keyword

### LINKED ISSUE #9806: gcc 7.2 compilation fails
### Description of the enhancement or error report

MOOSE framework compilation fails for me with
```
In file included from /h2/roystgnr/git/moose/modules/tensor_mechanics/include/materials/CompositeEigenstrain.h:11:0,
                 from /h2/roystgnr/git/moose/modules/tensor_mechanics/src/base/TensorMechanicsApp.C:57:
/h2/roystgnr/git/moose/framework/include/materials/CompositeTensorBase.h: In constructor ‘CompositeTensorBase<T, U>::CompositeTensorBase(const InputParameters&)’:
/h2/roystgnr/git/moose/framework/include/materials/CompositeTensorBase.h:83:60: error: expected ‘)’ before ‘::’ token
     _num_args(this->template DerivativeMaterialInterface<U>::coupledComponents("args")),
                                                            ^~
/h2/roystgnr/git/moose/framework/include/materials/CompositeTensorBase.h: In member function ‘void CompositeTensorBase<T, U>::initializeDerivativeProperties(std::__cxx11::string)’:
/h2/roystgnr/git/moose/framework/include/materials/CompositeTensorBase.h:117:54: error: expected ‘,’ or ‘;’ before ‘::’ token
         this->template DerivativeMaterialInterface<U>::getVar("args", j)->name();
                                                      ^~
/h2/roystgnr/git/moose/framework/include/materials/CompositeTensorBase.h:124:56: error: expected ‘,’ or ‘;’ before ‘::’ token
           this->template DerivativeMaterialInterface<U>::getVar("args", k)->name();
                                                        ^~
/h2/roystgnr/git/moose/framework/include/materials/CompositeTensorBase.h:143:56: error: expected ‘,’ or ‘;’ before ‘::’ token
           this->template DerivativeMaterialInterface<U>::getVar("args", j)->name();
                                                        ^~
/h2/roystgnr/git/moose/framework/include/materials/CompositeTensorBase.h:156:58: error: expected ‘,’ or ‘;’ before ‘::’ token
             this->template DerivativeMaterialInterface<U>::getVar("args", k)->name();
                                                          ^~
/h2/roystgnr/git/moose/framework/include/materials/CompositeTensorBase.h: In member function ‘virtual void CompositeTensorBase<T, U>::computeQpTensorProperties(MaterialProperty<P>&, libMesh::Real)’:
/h2/roystgnr/git/moose/framework/include/materials/CompositeTensorBase.h:172:72: error: expected ‘,’ or ‘;’ before ‘::’ token
   const unsigned int qp = this->template DerivativeMaterialInterface<U>::_qp;
```

### Rationale for the enhancement or information for reproducing the error

Switching to gcc 7.2 instead of 6.1 triggered the error for me; I believe that would be sufficient for others too.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Looking through C++ standards documents, it *appears* to me that the template keyword here, referring to a superclass, shouldn't be needed, because the superclass isn't a member template in need of a qualifier... but I and gcc 7 may be misunderstanding that (in which case this is not a bug, and "fixing" it would actually introduce a bug to other compilers) or other compilers may misunderstand that (in which case this code is a bug, but fixing it would break a workaround for other compilers).

### PR DESCRIPTION
**Pull request by roystgnr**
This lets MOOSE compile with gcc 7.2 for me, and so fixes #9806

We might want to give it some extra testing with more varied compilers
before merging though.

### CODE REVIEW

**Comment by dschwen** [comment]
Hmm, I added all these, and I think this was necessary for the compilers I used :-/

**Comment by roystgnr** [comment]
Are you sure *all* were necessary?  There are a number of ```this->template SomeMember<Foo>``` cases in the same file, and I'm pretty sure *those* were necessary; is it possible that while adding them you just went a little overboard?

**Comment by dschwen** [comment]
@roystgnr I think you are right. This should only be needed for templated _members_, right?

**Comment by roystgnr** [comment]
Hmm... actually, looking through git log, it seems that the "template" keyword came first, and the ```DerivativeMaterialInterface<U>::``` qualifier is what you added to fix Intel compilation.

I *believe* we need the keyword for templated members and not for subclasses, but that part of the C++ standard is a bit opaque to me, and even if I'm right, I'm sure users wouldn't be thrilled by "but our code is standard C++, your compiler is wrong!", so if this fix regresses other popular compilers then we probably need to figure out some different workaround instead.

**Comment by roystgnr** [comment]
Looks like we've compiled with your preferred versions of both Intel and gcc; I don't expect any problems with subsequent tests.  I'm going to kick a few of the optional tests in https://www.moosebuild.org/pr/4197/ (I think "Mac", "Minimum clang", and "Minimum gcc" should do it?) to try and make sure I'm not regressing slightly-less-preferred compiler versions either.

**Review by permcody — APPROVED** [review]
