### PR TITLE
C++20 warning fixes

### LINKED ISSUE #33015: MOOSE triggers compiler warnings with newer clang++ and newer C++ standards
### Bug Description

I want to use a recent Kokkos version requiring C++20.  I want to turn on `-Werror` so I can catch any compiler warnings along the way.  MOOSE fails to build with `clang++` 20.1.8 `-std=c++20` (or newer) with `-Werror` turned on, with e.g.
```
/tmp/build/moose/framework/contrib/hit/src/hit/lex.cc:16:19: error: unused variable 'newline' [-Werror,-Wunused-const-variable]
   16 | const std::string newline = "\n\r";
```

### Steps to Reproduce

See e.g. https://civet.inl.gov/job/3859397/; any build with a new enough `clang++ -std=c++20 -Werror` (or a higher standard) seems to be sufficient.

### Impact

Just an annoyance for now, but it may become a bigger deal when we start requiring C++20 for everyone.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by roystgnr**
This fixes #33015 for me. (at least in `dbg` mode, but surely we have no real `opt` mode code paths that aren't in `dbg` mode too; that'd be a different and more serious problem)

I had no idea there were only going to be two fixes here, or I would have just fixed them in May instead of turning off -Werror and letting my eyes glaze over warnings.

### CODE REVIEW

**Comment by loganharbour** [comment]
I believe the changes to lex.cc require us to rebuild the cython pyhit

**Review by GiudGiud — APPROVED** [review]

**Comment by roystgnr** [comment]
Those misc/signal_handler.test_signal failures seem repeatable but I don't see how they could possibly be related.

**Comment by GiudGiud** [comment]
not related
