### ISSUE TITLE
Any version-info failure silently disables all version/environment checks

### ISSUE THREAD

**Issue by jcphill** [idaholab/moose#33665]
### Bug Description

`premake.py`'s `PreMake` class clearly intends every version/environment check it does to be best-effort and non-fatal — `check()` wraps `self._check()` in a broad `try/except` that only ever warns:

```python
def check(self):
    try:
        self._check()
    except Exception as e:
        warning = "PreMake check failed; this may be ignored but may suggest an environment issue"
        ...
        self.warn(warning)
```

But `PreMake.__init__` builds its full package catalog *before* that tolerance kicks in, and with no per-package isolation:

```python
self.packages = Versioner().get_packages("HEAD")   # premake.py:28, unguarded
```

`get_packages()` (`versioner.py:549`) builds every configured package's info in a single pass over `versioner.yaml`'s `packages` dict, with no per-entry error handling. If any *one* package's info-gathering fails, the whole call raises and `self.packages` is never assigned — taking down every check that depends on it, including checks for packages that built successfully on their own and had nothing to do with the failure.

Concretely: the `"app"` package's name comes from `Versioner.get_app_info()`, which requires the current working directory to be inside a git working tree (returns `None` otherwise — `versioner.py:1052-1068`, `Union[AppInfo, None]`, so this is documented, expected behavior, not itself a bug). `get_packages()` doesn't check for that:

```python
"name": Versioner.get_app_info().name if name == "app" else name,   # versioner.py:583
```

giving `AttributeError: 'NoneType' object has no attribute 'name'` when invoked outside a git checkout (e.g., a build system that stages/mirrors an app's source tree without `.git` — how we hit this, via a CMake-based build for [Cardinal](https://github.com/neams-th-coe/cardinal)).

**Suggested fix:** give `get_packages()` per-package error isolation, so one package's failure doesn't block resolving the others at all — rather than just moving the failure point (wrapping `PreMake.__init__`'s call would only turn "some checks silently don't run" into "no checks silently run"):

```python
all_packages: list[str] = []
packages: dict[str, Package] = {}
failed: dict[str, Exception] = {}
for name, values in config.items():
    try:
        ...  # existing per-package construction, unchanged
        packages[name] = Package(**package)
        all_packages.append(name)
    except Exception as e:
        failed[name] = e
        continue

# A package that depends on one that failed can't be resolved either --
# surface that clearly rather than KeyError-ing in the topological sort
# or dependency-resolution steps below.
for name, package in packages.items():
    for dep in package.dependencies:
        if dep in failed:
            raise Exception(f"{name} depends on {dep}, which failed to build") from failed[dep]
```

with the rest of the function (topological sort, dependency resolution, influential-hash computation) unchanged — it already only ever iterates `packages.values()`, so entries that never made it in are simply and correctly absent.

Two call sites in `premake.py` should also be made tolerant of a package legitimately being absent from the result, so a package that failed to build doesn't introduce a *second* crash at the point it's consumed:
- `_checkCondaPackage` (`premake.py:228`): `versioner_package = self.packages[versioner_name]` → `self.packages.get(versioner_name)`, skip the check if `None` (matches how `_checkApptainer` already does this).
- `PreMake.__init__` itself can then drop any guard around `Versioner().get_packages("HEAD")` entirely — it always returns successfully now; only the checks that actually depend on a package that failed to build (currently: none for `"app"` specifically, since it's a leaf nothing else depends on) skip cleanly instead of the whole catalog vanishing.

### Steps to Reproduce

```
git clone --depth 1 https://github.com/idaholab/moose.git /tmp/moose_repro
cd /tmp   # anywhere not inside a git repository
python3 /tmp/moose_repro/scripts/premake.py
```

```
Traceback (most recent call last):
  File ".../scripts/premake.py", line 273, in <module>
    PreMake().check()
    ~~~~~~~^^
  File ".../scripts/premake.py", line 28, in __init__
    self.packages = Versioner().get_packages("HEAD")
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File ".../scripts/versioner.py", line 583, in get_packages
    "name": Versioner.get_app_info().name if name == "app" else name,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
```

MOOSE commit used above: `e524555a283187fee02ca89220d0d7eb3bb68cd4`.

### Impact

In a real build (e.g. Cardinal's) this traceback prints and the build continues regardless, since the calling Makefile doesn't treat `premake.py`'s exit status as fatal — but *every* check `PreMake` was meant to perform silently never happens, with no indication anything was skipped beyond the traceback itself scrolling past in build output.

This is worse than it looks in an environment like the one in the Diagnostics below: this container sets `MOOSE_APPTAINER_GENERATOR_LIBRARY=moose-dev` and related tag variables, so `PreMake._checkApptainer()` *would* run and only needs the `"moose-dev"` package's info — which builds independently of `"app"` and has everything it needs to succeed. But because `get_packages()` fails outright on the unrelated `"app"` entry before returning anything, `self.packages` never gets set, and the `moose-dev` apptainer-tag consistency check — a genuinely useful check, fully satisfiable in this environment — never runs either. The failure of one package's metadata silently disables validation of every other package, including ones that had nothing to do with the failure and would otherwise have caught a real mismatch.

### [Optional] Diagnostics

Output of `./scripts/diagnostics.sh`, run from within the `moose-dev` apptainer container (`moose-dev-rocky8-gcc-openmpi-x86_64_v3:2026.08.23`) used above:

```
################################################################################
Influential Environment Variables

APPTAINER_APPNAME=
APPTAINER_BIND=/work
APPTAINER_COMMAND=exec
APPTAINER_CONTAINER=/tmp/moose-dev-oras-8-23
APPTAINER_ENVIRONMENT=/.singularity.d/env/91-environment.sh
APPTAINER_NAME=moose-dev-oras-8-23
CC=mpicc
CONDA_CHANNEL=https://conda.software.inl.gov/public
CURL_CA_BUNDLE=
CXX=mpicxx
F77=mpif77
F90=mpif90
FC=mpif90
LD_LIBRARY_PATH=/opt/mpich/lib:/opt/rh/gcc-toolset-13/root/usr/lib64:/opt/rh/gcc-toolset-13/root/usr/lib:/.singularity.d/libs
LIBMESH_DIR=/opt/libmesh
MODULESHOME=/usr/share/lmod/lmod
MOOSE_APPTAINER_GENERATOR_LIBRARY=moose-dev
MOOSE_APPTAINER_GENERATOR_MOOSE_VERSION=b6f1f598f8407410eee441c601bd0a7fb2639f61
MOOSE_APPTAINER_GENERATOR_NAME=moose-dev-rocky8-gcc-openmpi-x86_64_v3
MOOSE_APPTAINER_GENERATOR_NAME_SUMMARY=moose-dev-rocky8-gcc-openmpi-x86_64_v3:2026.08.23
MOOSE_APPTAINER_GENERATOR_TAG=2026.08.23
MOOSE_APPTAINER_GENERATOR_VERSION=2026.08.23
MOOSE_JOBS=6
MOOSE_OPENMPI_DIR=/opt/openmpi
PATH=/opt/wasp/bin:/opt/code-server/bin:/opt/python/bin:/opt/openmpi/bin:/opt/rh/gcc-toolset-13/root/usr/bin:/opt/valgrind/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PETSC_DIR=/opt/petsc
REQUESTS_CA_BUNDLE=
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_MPI_TYPE=cray_shasta
SSL_CERT_FILE=
WASP_DIR=/opt/wasp
################################################################################
Compiler(s) (CC CXX FC F77 F90):

which $CC; /opt/openmpi/bin/mpicc
$CC --version; gcc (GCC) 13.3.1 20240611 (Red Hat 13.3.1-2)
$CC -show; gcc -I/opt/openmpi/include -pthread -L/opt/openmpi/lib -Wl,-rpath -Wl,/opt/openmpi/lib -Wl,--enable-new-dtags -lmpi

which $CXX; /opt/openmpi/bin/mpicxx
$CXX --version; g++ (GCC) 13.3.1 20240611 (Red Hat 13.3.1-2)
$CXX -show; g++ -I/opt/openmpi/include -pthread -L/opt/openmpi/lib -Wl,-rpath -Wl,/opt/openmpi/lib -Wl,--enable-new-dtags -lmpi

which $FC; /opt/openmpi/bin/mpif90
$FC --version; GNU Fortran (GCC) 13.3.1 20240611 (Red Hat 13.3.1-2)
$FC -show; gfortran -I/opt/openmpi/include -pthread -I/opt/openmpi/lib -L/opt/openmpi/lib -Wl,-rpath -Wl,/opt/openmpi/lib -Wl,--enable-new-dtags -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi

which $F77; /opt/openmpi/bin/mpif77
$F77 --version; GNU Fortran (GCC) 13.3.1 20240611 (Red Hat 13.3.1-2)
$F77 -show; gfortran -I/opt/openmpi/include -pthread -I/opt/openmpi/lib -L/opt/openmpi/lib -Wl,-rpath -Wl,/opt/openmpi/lib -Wl,--enable-new-dtags -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi

which $F90; /opt/openmpi/bin/mpif90
$F90 --version; GNU Fortran (GCC) 13.3.1 20240611 (Red Hat 13.3.1-2)
$F90 -show; gfortran -I/opt/openmpi/include -pthread -I/opt/openmpi/lib -L/opt/openmpi/lib -Wl,-rpath -Wl,/opt/openmpi/lib -Wl,--enable-new-dtags -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi

OK
################################################################################
Python Sanity Checks

/usr/bin/env python3 --version; (reporting as: Python 3.14.7) matches
which python3 python;

/opt/python/bin/python3 --version; == Python 3.14.7
/opt/python/bin/python --version; == Python 3.14.7

OK
################################################################################
Python Modules (TestHarness, run-ability)

OK


checks PASSED
```

Note the `MOOSE_APPTAINER_GENERATOR_*` variables above — this is exactly what makes `apptainer_env` truthy and `_checkApptainer()` eligible to run in `PreMake._check()`, confirming the Impact described above is real in this environment, not hypothetical.
