### ISSUE TITLE
Can't build moose with gcc on Mac (due to exodiff)

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#10813]
## Rationale

Can't build with gcc 7.2.0 on Sierra. Probably fails on High Sierra as well.

## Description

```
/Users/algebk-mac/projects/moose/framework/contrib/exodiff/exodiff.C:1021:36: error: ‘int isnan(double)’ conflicts with a previous declaration
   extern "C" int isnan(double value);
                                    ^
In file included from /opt/moose/gcc-7.2.0/include/c++/7.2.0/math.h:36:0,
                 from /Users/algebk-mac/projects/moose/framework/contrib/exodiff/exodiff.C:39:
/opt/moose/gcc-7.2.0/include/c++/7.2.0/cmath:626:3: note: previous declaration ‘constexpr bool std::isnan(double)’
   isnan(double __x)
   ^~~~~
/Users/algebk-mac/projects/moose/framework/contrib/exodiff/exodiff.C: In function ‘bool Invalid_Values(const double*, size_t)’:
/Users/algebk-mac/projects/moose/framework/contrib/exodiff/exodiff.C:1040:25: error: call of overloaded ‘isnan(const double&)’ is ambiguous
      if (isnan(values[i]))
                         ^
/Users/algebk-mac/projects/moose/framework/contrib/exodiff/exodiff.C:1021:18: note: candidate: int isnan(double)
   extern "C" int isnan(double value);
                  ^~~~~
In file included from /opt/moose/gcc-7.2.0/include/c++/7.2.0/math.h:36:0,
                 from /Users/algebk-mac/projects/moose/framework/contrib/exodiff/exodiff.C:39:
/opt/moose/gcc-7.2.0/include/c++/7.2.0/cmath:631:3: note: candidate: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^~~~~
/opt/moose/gcc-7.2.0/include/c++/7.2.0/cmath:626:3: note: candidate: constexpr bool std::isnan(double)
   isnan(double __x)
   ^~~~~
/opt/moose/gcc-7.2.0/include/c++/7.2.0/cmath:618:3: note: candidate: constexpr bool std::isnan(float)
   isnan(float __x)
   ^~~~~
```

## Impact

Allow building with gcc on mac.

**Comment by permcody** [comment]
@brianmoose - How did you get this far? What version of Xcode do you have? I'd be willing to just patch Exodiff to get us around this problem. We could drop Exodiff's isnan method and just use the C++11 builtin.

**Comment by milljm** [comment]
It fails on High Sierra in the exact same way.

**Comment by permcody** [comment]
Superseded by #10817
