### ISSUE TITLE
Eigen 3.4.0 compatibility fix

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#20869]
## Reason
`Eigen::DontAlign` seems to cause issues with `Eigen::SelfAdjointEigenSolver`
Resulting in 

```
/home/schwd/Programs/libmesh/installed/include/Eigen/src/Eigenvalues/Tridiagonalization.h: In instantiation of 'void Eigen::internal::tridiagonalization_inplace(MatrixType&, DiagonalType&, SubDiagonalType&, CoeffVectorType&, bool) [with MatrixType = Eigen::Matrix<double, 6, 6, 0, 6, 6>; DiagonalType = Eigen::Matrix<double, 6, 1, 0, 6, 1>; SubDiagonalType = Eigen::Matrix<double, 5, 1, 2, 5, 1>; CoeffVectorType = Eigen::Matrix<double, 5, 1, 2, 5, 1>]':
/home/schwd/Programs/libmesh/installed/include/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:458:39:   required from 'Eigen::SelfAdjointEigenSolver<MatrixType>& Eigen::SelfAdjointEigenSolver<_MatrixType>::compute(const Eigen::EigenBase<OtherDerived>&, int) [with InputType = Eigen::Matrix<double, 6, 6, 2>; _MatrixType = Eigen::Matrix<double, 6, 6, 2>]'
/home/schwd/Programs/libmesh/installed/include/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:181:14:   required from 'Eigen::SelfAdjointEigenSolver<_MatrixType>::SelfAdjointEigenSolver(const Eigen::EigenBase<OtherDerived>&, int) [with InputType = Eigen::Matrix<double, 6, 6, 2>; _MatrixType = Eigen::Matrix<double, 6, 6, 2>]'
/home/schwd/Programs/moose/modules/tensor_mechanics/src/materials/ADHillElastoPlasticityStressUpdate.C:147:59:   required from here
/home/schwd/Programs/libmesh/installed/include/Eigen/src/Eigenvalues/Tridiagonalization.h:434:55: error: no matching function for call to 'Eigen::internal::tridiagonalization_inplace_selector<Eigen::Matrix<double, 6, 6, 0, 6, 6>, 6, false>::run(Eigen::Matrix<double, 6, 6, 0, 6, 6>&, Eigen::Matrix<double, 6, 1, 0, 6, 1>&, Eigen::Matrix<double, 5, 1, 2, 5, 1>&, Eigen::Matrix<double, 5, 1, 2, 5, 1>&, bool&)'
  434 |   tridiagonalization_inplace_selector<MatrixType>::run(mat, diag, subdiag, hcoeffs, extractQ);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Design
Remove `Eigen::DontAlign`

## Impact
Code will build with Eigen 3.4.0
