### ISSUE TITLE
MOOSE triggers compiler warnings with newer clang++ and newer C++ standards

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#33015]
### Bug Description

I want to use a recent Kokkos version requiring C++20.  I want to turn on `-Werror` so I can catch any compiler warnings along the way.  MOOSE fails to build with `clang++` 20.1.8 `-std=c++20` (or newer) with `-Werror` turned on, with e.g.
```
/tmp/build/moose/framework/contrib/hit/src/hit/lex.cc:16:19: error: unused variable 'newline' [-Werror,-Wunused-const-variable]
   16 | const std::string newline = "\n\r";
```

### Steps to Reproduce

See e.g. https://civet.inl.gov/job/3859397/; any build with a new enough `clang++ -std=c++20 -Werror` (or a higher standard) seems to be sufficient.

### Impact

Just an annoyance for now, but it may become a bigger deal when we start requiring C++20 for everyone.
